### PR TITLE
Problem statement folder improvement

### PR DESCRIPTION
**Pull request by Yulia-Sych**
Add some information to research question and rewrite retrospective file. Fill it out with general information from the whole team instead of some pieces of information from each team member.

### CODE REVIEW

**Comment by tvsirius** [comment]
Look, there is still ```data_analysis``` folder here, but as agreed it is now ```1_data_analysis``` so please rename it
Other thing there is ```.idea``` and ```shelf``` folders and we don't need them. It's temporary files for PyCharm
We should make ```.gitignore``` file like this, and git would not add this files. 
```
.env
.idea
shelf
```

I see we already have ```.idea``` so we will remove it anyway, but rename folder  ```data_analysis``` to ```1_data_analysis```, we don't need different copies of code in similar folders.

**Comment by tvsirius** [comment]
it's better, but you are still experiencing some trouble with different branches. Why you remove some persons time from collaboration folder.
and you should include relative path in the README.md for milestone 1

**Comment by Yulia-Sych** [comment]
> it's better, but you are still experiencing some trouble with different branches. Why you remove some persons time from collaboration folder. and you should include relative path in the README.md for milestone 1

It seems I still have issue with branches. Now, I found that I have the oldest version of communication.md, but I updated it yesterday. Will try to solve.

**Comment by tvsirius** [comment]
Hi, we just need 1_problem_identification to be updated for current work, do you have any success?

**Pull request merged**
