### PR TITLE
Milestone2 dataset description

### PR DESCRIPTION
**Pull request by Wagoory**
Worked on the kaggle mental health data set discription
I created a dir for the data_collection and worked on it

### CODE REVIEW

**Comment by tvsirius** [comment]
Looks live our research will be hold on several datasets. Maybe it would be wise to make several .md files for each (with corresponding name), and a general README.md for this milestone.
If you agree can you rename ```Data_Set_Discription.md``` to ```Global_Trends_in_Mental_Health_Dataset_Discription.md``` ?
And we will add addtional descriptions here

**Comment by Wagoory** [comment]
Okay I'll work on that

**Comment by Wagoory** [comment]
i fixed the file name

**Review by tvsirius — APPROVED** [review]
Super!

**Pull request merged**
